[project]
name = "p1-ecommerce-automation"
version = "0.1.0"
description = "API test automation project for an e-commerce system"
requires-python = ">=3.12"
dependencies=[
    "requests",
    "python-dotenv"
]

[project.optional-dependencies]
test = [
    "pytest"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]